import '../styles/globals.css';
import type { Metadata } from 'next';
import { Syne } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';

const syne = Syne({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={syne.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
