export const cuisines = [
  {
    value: 'appetizers',
    label: 'Appetizers',
    icon: 'link_to_appetizers_svg_icon',
    description: 'Delicious bites to kick off the meal.',
  },
  {
    value: 'soups',
    label: 'Soups',
    icon: 'link_to_soups_svg_icon',
    description: 'Hearty bowls of warmth and flavor.',
  },
  {
    value: 'salads',
    label: 'Salads',
    icon: 'link_to_salads_svg_icon',
    description: 'Fresh greens and tasty accompaniments.',
  },
  {
    value: 'meat',
    label: 'Meat',
    icon: 'link_to_meat_main_dish_svg_icon',
    description: 'Savory meat-based main courses.',
  },
  {
    value: 'seafood',
    label: 'Seafood',
    icon: 'link_to_seafood_main_dish_svg_icon',
    description: 'Ocean-inspired main dishes.',
  },
  {
    value: 'vegetarian',
    label: 'Vegetarian',
    icon: 'link_to_vegetarian_main_dish_svg_icon',
    description: 'Veggie-centric main course options.',
  },
  {
    value: 'pasta',
    label: 'Pasta',
    icon: 'link_to_pasta_svg_icon',
    description: 'Noodles and pasta-based dishes.',
  },
  {
    value: 'breads',
    label: 'Breads',
    icon: 'link_to_breads_svg_icon',
    description: 'Freshly baked bread and baked goods.',
  },
  {
    value: 'desserts',
    label: 'Desserts',
    icon: 'link_to_desserts_svg_icon',
    description: 'Sweet treats to satisfy your cravings.',
  },
  {
    value: 'beverages',
    label: 'Beverages',
    icon: 'link_to_beverages_svg_icon',
    description: 'Quench your thirst with delightful drinks.',
  },
  {
    value: 'breakfast',
    label: 'Breakfast',
    icon: 'link_to_breakfast_svg_icon',
    description: 'Morning delights to start your day.',
  },
  {
    value: 'snacks',
    label: 'Snacks',
    icon: 'link_to_snacks_svg_icon',
    description: 'Small bites for on-the-go satisfaction.',
  },
  {
    value: 'grilling',
    label: 'Grilling',
    icon: 'link_to_grilling_svg_icon',
    description: 'Sizzling and flavorful grilled dishes.',
  },
  {
    value: 'holiday',
    label: 'Holiday',
    icon: 'link_to_holiday_specials_svg_icon',
    description: 'Special dishes for festive occasions.',
  },
  {
    value: 'healthy',
    label: 'Healthy',
    icon: 'link_to_healthy_cuisine_svg_icon',
    description: 'Nutrient-packed and wholesome creations.',
  },
  {
    value: 'quick',
    label: 'Quick',
    icon: 'link_to_quick_meals_svg_icon',
    description: 'Recipes that come together in a flash.',
  },
  {
    value: 'dips',
    label: 'Dips',
    icon: 'link_to_dips_svg_icon',
    description: 'Savory dips and condiments.',
  },
  {
    value: 'sweets',
    label: 'Sweets',
    icon: 'link_to_sweets_svg_icon',
    description: 'Delectable desserts and sugary delights.',
  },
  {
    value: 'global',
    label: 'Global',
    icon: 'link_to_global_cuisine_svg_icon',
    description: 'Diverse flavors from around the world.',
  },
  {
    value: 'special',
    label: 'Special',
    icon: 'link_to_special_occasions_svg_icon',
    description: 'For those unforgettable occasions.',
  },
];
